# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SWIFT41JsonDecoder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SWIFT41JsonDecoder
pod 'Alamofire'
end
